<a href="https://colab.research.google.com/github/ujjwalbhatnagar/Analysis-on-Weather-Data/blob/main/Data_Analysis_on_Weather_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [11]:
from google.colab import files
 
 
uploaded = files.upload()

Saving WeatherData.csv to WeatherData.csv

In [12]:
import io
data = pd.read_csv(io.BytesIO(uploaded['WeatherData.csv']))

In [13]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [32]:
data.tail()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [16]:
data.shape

(8784, 8)

In [17]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [18]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [19]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

**.unique()**

In a column, it shows all the unique values. It can be applied on a single column only, not on the whole dataframe.

In [23]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

**.nunique()**

It shows the total no. of unique values in each column. It can be applied on a single column as well as on whole dataframe.

In [24]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [26]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

**.value_counts**

In a column, it shows all the unique with their count. It can be applied on single column only.

In [30]:
data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

**Q) Find all the unique 'wind speed' values in the data.**

In [31]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

**Q) Find the no. of times when the 'Weather is exactly Clear'.**

In [44]:
data[data.Weather == 'Clear'].value_counts()

Date/Time        Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  Visibility_km  Press_kPa  Weather
1/11/2012 1:00   -10.7   -17.8             56         17               25.0           101.49     Clear      1
6/14/2012 3:00    12.3    5.3              62         13               25.0           101.96     Clear      1
6/14/2012 23:00   19.6    5.8              40         6                25.0           102.21     Clear      1
6/14/2012 22:00   20.2    6.0              39         9                25.0           102.20     Clear      1
6/14/2012 21:00   21.0    6.0              38         11               25.0           102.16     Clear      1
                                                                                                           ..
2/4/2012 19:00   -7.7    -14.0             61         7                25.0           101.97     Clear      1
2/4/2012 18:00   -6.6    -13.7             57         9                25.0           101.96     Clear      1
2/4/2012 17:00   -6.2    -13.5             56         11               48.3           101.97     Clear      1
2/4/2012 16:00   -5.7    -12.8             57         9                48.3           101.99     Clear      1
9/9/2012 5:00     11.5    9.5              88         11               25.0           100.44     Clear      1
Length: 1326, dtype: int64

In [46]:
data.groupby('Weather').get_group('Clear').count() #get_group gets a particular variable from row dataset.

Date/Time           1326
Temp_C              1326
Dew Point Temp_C    1326
Rel Hum_%           1326
Wind Speed_km/h     1326
Visibility_km       1326
Press_kPa           1326
Weather             1326
dtype: int64

**Q) Find the number of times when the 'Wind Speed was exactly 4 km/h.**

In [52]:
data[data['Wind Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

**Q) Find out all the Null Values in the data.**

In [54]:
data.isnull()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

In [55]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [56]:
data.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

**Q) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.**

In [78]:
data.rename(columns = {'Weather Condition' : 'WC'}, inplace=True)

In [79]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,WC
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

**Q) What is the mean 'Visibility'?**

In [67]:
data['Visibility_km'].mean()

27.66444672131151

**Q) What is the Standard Deviation of 'Pressure' in data?**

In [68]:
data['Press_kPa'].std()

0.8440047459486474

**Q) What is the Variance of 'Realtive Humidity' in data?**

In [69]:
data['Rel Hum_%'].var()

286.2485501984998

**Q) Find all instances when 'Snow' was recorded.**

In [81]:
data[data.WC == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,WC
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [95]:
data[data['WC'].str.contains('Snow')].head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,WS,Visibility_km,Press_kPa,WC
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers

**Q) Find all the instances when 'Wind Speed' is above 24' and 'Visibility is 25'.**

In [88]:
data.rename(columns ={'Wind Speed_km/h' : 'WS'}, inplace=True)

In [97]:
data[(data['WS'] > 24) & (data['Visibility_km'] ==25)].head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,WS,Visibility_km,Press_kPa,WC
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy

**Q) What is the mean value of each column against each 'Weather Condition'?**

In [107]:
data.groupby('WC').mean().head()

,Temp_C,Dew Point Temp_C,Rel Hum_%,WS,Visibility_km,Press_kPa
WC,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000

Q)What is the Min and Max value of each column against each 'Weather Condition'?

In [118]:
data.groupby('WC').max()
y = data.groupby('WC').min()
res = (x,y)
res

(                                                Date/Time  Temp_C  \
 WC
 Clear                                       9/9/2012 5:00    32.8
 Cloudy                                     9/9/2012 23:00    30.5
 Drizzle                                    9/30/2012 3:00    18.8
 Drizzle,Fog                                9/30/2012 2:00    19.9
 Drizzle,Ice Pellets,Fog                   12/17/2012 9:00     0.4
 Drizzle,Snow                             12/19/2012 18:00     1.2
 Drizzle,Snow,Fog                          12/22/2012 3:00     1.1
 Fog                                        9/22/2012 0:00    20.8
 Freezing Drizzle                            2/1/2012 5:00    -2.3
 Freezing Drizzle,Fog                      12/10/2012 5:00    -0.3
 Freezing Drizzle,Haze                      2/1/2012 13:00    -5.0
 Freezing Drizzle,Snow                      3/2/2012 12:00    -3.3
 Freezing Fog                               3/17/2012 6:00    -0.1
 Freezing Rain                               2/1/2012 7:00     0.3
 Freezing Rain,Fog                         12/17/2012 1:00     0.1
 Freezing Rain,Haze                         2/1/2012 15:00    -4.9
 Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00    -2.6
 Freezing Rain,Snow Grains                  1/13/2012 9:00    -5.0
 Haze                                      3/13/2012 23:00    14.1
 Mainly Clear                                9/9/2012 9:00    33.0
 Moderate Rain,Fog                         12/10/2012 8:00     1.7
 Moderate Snow                             12/27/2012 9:00    -4.9
 Moderate Snow,Blowing Snow               12/27/2012 12:00    -5.4
 Mostly Cloudy                               9/9/2012 2:00    32.4
 Rain                                        9/5/2012 2:00    22.8
 Rain Showers                               9/8/2012 16:00    26.4
 Rain Showers,Fog                          10/20/2012 3:00    12.8
 Rain Showers,Snow Showers                 12/5/2012 10:00     2.2
 Rain,Fog                                  9/30/2012 23:00    21.7
 Rain,Haze                                  3/13/2012 9:00     5.5
 Rain,Ice Pellets                          12/18/2012 5:00     0.6
 Rain,Snow                                  4/23/2012 3:00     1.7
 Rain,Snow Grains                          12/21/2012 0:00     1.9
 Rain,Snow,Fog                             12/8/2012 21:00     0.8
 Rain,Snow,Ice Pellets                     12/21/2012 5:00     1.3
 Snow                                       4/27/2012 9:00     3.7
 Snow Pellets                             11/24/2012 15:00     0.7
 Snow Showers                               3/4/2012 21:00     2.9
 Snow Showers,Fog                         12/29/2012 13:00   -10.0
 Snow,Blowing Snow                          2/25/2012 9:00    -1.4
 Snow,Fog                                  3/14/2012 19:00     1.1
 Snow,Haze                                  2/1/2012 21:00    -3.6
 Snow,Ice Pellets                            3/3/2012 4:00     0.8
 Thunderstorms                              7/4/2012 16:00    26.7
 Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    10.9
 Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    19.6
 Thunderstorms,Rain                        7/23/2012 18:00    21.3
 Thunderstorms,Rain Showers                  9/8/2012 4:00    25.5
 Thunderstorms,Rain Showers,Fog            7/31/2012 20:00    22.9
 Thunderstorms,Rain,Fog                     7/17/2012 5:00    20.6

                                          Dew Point Temp_C  Rel Hum_%  WS  \
 WC
 Clear                                                20.4         99  33
 Cloudy                                               22.6         99  54
 Drizzle                                              17.7         96  30
 Drizzle,Fog                                          19.1        100  28
 Drizzle,Ice Pellets,Fog                              -0.7         92  20
 Drizzle,Snow                                          0.2         95  19
 Drizzle,Snow,Fog                                      0.6         98  32
 Fog                                                  19.6        100  22
 Freezing Drizzle                                     -3.3         93  26
 Freezing Drizzle,Fog                                 -2.3         94  33
 Freezing Drizzle,Haze                                -7.7         83  11
 Freezing Drizzle,Snow                                -4.6         94  24
 Freezing Fog                                         -0.3         99   9
 Freezing Rain                                        -1.7         92  28
 Freezing Rain,Fog                                    -0.9         93  26
 Freezing Rain,Haze                                   -7.4         83   9
 Freezing Rain,Ice Pellets,Fog                        -3.7         92  28
 Freezing Rain,Snow Grains                            -7.3         84  32
 Haze                                                 11.1         86  17
 Mainly Clear                                         21.2         99  63
 Moderate Rain,Fog                                     0.8         94  17
 Moderate Snow                                        -6.7         93  39
 Moderate Snow,Blowing Snow                           -6.4         93  41
 Mostly Cloudy                                        24.4        100  83
 Rain                                                 20.4         99  52
 Rain Showers                                         23.0         97  41
 Rain Showers,Fog                                     12.1         96  13
 Rain Showers,Snow Showers                            -1.2         78  28
 Rain,Fog                                             19.5        100  46
 Rain,Haze                                             2.9         86  17
 Rain,Ice Pellets                                     -0.6         92  24
 Rain,Snow                                             0.5         94  52
 Rain,Snow Grains                                     -2.1         75  26
 Rain,Snow,Fog                                         0.3         96   9
 Rain,Snow,Ice Pellets                                 0.1         94  28
 Snow                                                  0.3         96  57
 Snow Pellets                                         -6.4         59  35
 Snow Showers                                         -0.7         94  37
 Snow Showers,Fog                                    -11.1         92  22
 Snow,Blowing Snow                                    -2.9         91  48
 Snow,Fog                                              0.8         99  35
 Snow,Haze                                            -6.4         81  15
 Snow,Ice Pellets                                     -1.7         92  33
 Thunderstorms                                        20.1         87  15
 Thunderstorms,Heavy Rain Showers                      9.0         88   9
 Thunderstorms,Moderate Rain Showers,Fog              18.5         93  15
 Thunderstorms,Rain                                   19.1         93  30
 Thunderstorms,Rain Showers                           23.1         98  32
 Thunderstorms,Rain Showers,Fog                       21.3         91  35
 Thunderstorms,Rain,Fog                               18.6         88  19

                                          Visibility_km  Press_kPa
 WC
 Clear                                             48.3     103.63
 Cloudy                                            48.3     103.65
 Drizzle                                           25.0     101.56
 Drizzle,Fog                                        9.7     102.07
 Drizzle,Ice Pellets,Fog                            4.0     100.79
 Drizzle,Snow                                      11.3     101.15
 Drizzle,Snow,Fog                                   9.7     100.15
 Fog                                                9.7     103.04
 Freezing Drizzle                                  12.9     101.02
 Freezing Drizzle,Fog                               8.0     101.27
 Freezing Drizzle,Haze                              4.0     100.36
 Freezing Drizzle,Snow                             12.9     101.18
 Freezing Fog                                       0.8     102.85
 Freezing Rain                                     16.1     101.00
 Freezing Rain,Fog                                  9.7     101.01
 Freezing Rain,Haze                                 2.8     100.41
 Freezing Rain,Ice Pellets,Fog                      8.0     100.95
 Freezing Rain,Snow Grains                          4.8      98.56
 Haze                                               9.7     102.97
 Mainly Clear                                      48.3     103.59
 Moderate Rain,Fog                                  6.4      99.98
 Moderate Snow                                      0.8     100.67
 Moderate Snow,Blowing Snow                         0.6     100.64
 Mostly Cloudy                                     48.3     103.65
 Rain                                              48.3     102.26
 Rain Showers                                      48.3     102.31
 Rain Showers,Fog                                   6.4      99.83
 Rain Showers,Snow Showers                         24.1     101.11
 Rain,Fog                                           9.7     101.77
 Rain,Haze                                          9.7     100.61
 Rain,Ice Pellets                                   9.7     100.12
 Rain,Snow                                         25.0     101.07
 Rain,Snow Grains                                  25.0     100.60
 Rain,Snow,Fog                                      6.4     100.73
 Rain,Snow,Ice Pellets                              6.4     100.47
 Snow                                              25.0     102.73
 Snow Pellets                                       2.4      99.70
 Snow Showers                                      48.3     102.50
 Snow Showers,Fog                                   9.7     102.52
 Snow,Blowing Snow                                  9.7     100.62
 Snow,Fog                                           9.7     102.07
 Snow,Haze                                          6.4     100.99
 Snow,Ice Pellets                                  11.3     100.96
 Thunderstorms                                     25.0     100.62
 Thunderstorms,Heavy Rain Showers                   2.4     100.26
 Thunderstorms,Moderate Rain Showers,Fog            3.2     100.01
 Thunderstorms,Rain                                24.1     100.83
 Thunderstorms,Rain Showers                        25.0     101.06
 Thunderstorms,Rain Showers,Fog                     9.7     100.64
 Thunderstorms,Rain,Fog                             4.8     100.08  ,
                                                 Date/Time  Temp_C  \
 WC
 Clear                                      1/11/2012 1:00   -23.3
 Cloudy                                     1/1/2012 17:00   -21.4
 Drizzle                                   1/23/2012 21:00     1.1
 Drizzle,Fog                               1/23/2012 20:00     0.0
 Drizzle,Ice Pellets,Fog                   12/17/2012 9:00     0.4
 Drizzle,Snow                             12/17/2012 15:00     0.9
 Drizzle,Snow,Fog                         12/18/2012 21:00     0.3
 Fog                                         1/1/2012 0:00   -16.0
 Freezing Drizzle                          1/13/2012 10:00    -9.0
 Freezing Drizzle,Fog                        1/1/2012 2:00    -6.4
 Freezing Drizzle,Haze                      2/1/2012 11:00    -5.8
 Freezing Drizzle,Snow                      1/13/2012 3:00    -8.3
 Freezing Fog                               1/22/2012 6:00   -19.0
 Freezing Rain                             1/13/2012 11:00    -6.5
 Freezing Rain,Fog                         1/17/2012 23:00    -6.1
 Freezing Rain,Haze                         2/1/2012 14:00    -4.9
 Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00    -2.6
 Freezing Rain,Snow Grains                  1/13/2012 9:00    -5.0
 Haze                                      1/22/2012 12:00   -11.5
 Mainly Clear                              1/10/2012 11:00   -22.8
 Moderate Rain,Fog                         12/10/2012 8:00     1.7
 Moderate Snow                             1/12/2012 15:00    -6.3
 Moderate Snow,Blowing Snow               12/27/2012 10:00    -5.5
 Mostly Cloudy                              1/1/2012 16:00   -23.2
 Rain                                       1/1/2012 18:00     0.3
 Rain Showers                               1/1/2012 22:00     1.6
 Rain Showers,Fog                          10/20/2012 3:00    12.8
 Rain Showers,Snow Showers                  11/4/2012 8:00     2.1
 Rain,Fog                                  1/23/2012 18:00     0.0
 Rain,Haze                                  3/13/2012 7:00     4.0
 Rain,Ice Pellets                          12/18/2012 5:00     0.6
 Rain,Snow                                  1/10/2012 5:00     0.6
 Rain,Snow Grains                          12/21/2012 0:00     1.9
 Rain,Snow,Fog                             12/8/2012 21:00     0.8
 Rain,Snow,Ice Pellets                     12/21/2012 1:00     0.9
 Snow                                       1/10/2012 1:00   -16.7
 Snow Pellets                             11/24/2012 15:00     0.7
 Snow Showers                               1/12/2012 7:00   -13.3
 Snow Showers,Fog                          12/26/2012 9:00   -11.3
 Snow,Blowing Snow                         1/13/2012 21:00   -12.0
 Snow,Fog                                 12/16/2012 15:00   -10.1
 Snow,Haze                                  2/1/2012 17:00    -4.3
 Snow,Ice Pellets                          12/10/2012 3:00    -4.3
 Thunderstorms                              7/16/2012 1:00    21.6
 Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    10.9
 Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    19.6
 Thunderstorms,Rain                        5/25/2012 20:00    19.4
 Thunderstorms,Rain Showers                5/29/2012 16:00    11.0
 Thunderstorms,Rain Showers,Fog             6/29/2012 3:00    19.5
 Thunderstorms,Rain,Fog                     7/17/2012 5:00    20.6

                                          Dew Point Temp_C  Rel Hum_%  WS  \
 WC
 Clear                                               -28.5         20   0
 Cloudy                                              -26.8         18   0
 Drizzle                                              -0.2         74   0
 Drizzle,Fog                                          -1.6         85   0
 Drizzle,Ice Pellets,Fog                              -0.7         92  20
 Drizzle,Snow                                          0.1         92   9
 Drizzle,Snow,Fog                                     -0.1         92   7
 Fog                                                 -17.2         80   0
 Freezing Drizzle                                    -12.2         78   6
 Freezing Drizzle,Fog                                 -9.0         82   6
 Freezing Drizzle,Haze                                -8.3         81   9
 Freezing Drizzle,Snow                               -10.4         79   6
 Freezing Fog                                        -22.9         71   0
 Freezing Rain                                        -9.0         81   7
 Freezing Rain,Fog                                    -8.7         82   7
 Freezing Rain,Haze                                   -7.5         82   6
 Freezing Rain,Ice Pellets,Fog                        -3.7         92  28
 Freezing Rain,Snow Grains                            -7.3         84  32
 Haze                                                -16.0         68   0
 Mainly Clear                                        -28.0         20   0
 Moderate Rain,Fog                                     0.8         94  17
 Moderate Snow                                        -7.6         83  26
 Moderate Snow,Blowing Snow                           -6.6         92  39
 Mostly Cloudy                                       -28.5         18   0
 Rain                                                 -5.7         40   0
 Rain Showers                                         -7.2         37   0
 Rain Showers,Fog                                     12.1         96  13
 Rain Showers,Snow Showers                            -1.8         75  17
 Rain,Fog                                             -1.2         83   0
 Rain,Haze                                             1.0         81   7
 Rain,Ice Pellets                                     -0.6         92  24
 Rain,Snow                                            -1.7         81  13
 Rain,Snow Grains                                     -2.1         75  26
 Rain,Snow,Fog                                         0.3         96   9
 Rain,Snow,Ice Pellets                                -0.7         88  17
 Snow                                                -24.6         41   0
 Snow Pellets                                         -6.4         59  35
 Snow Showers                                        -19.3         52   0
 Snow Showers,Fog                                    -12.7         89   7
 Snow,Blowing Snow                                   -16.2         70  24
 Snow,Fog                                            -12.0         77   4
 Snow,Haze                                            -7.2         80   0
 Snow,Ice Pellets                                     -5.9         76  19
 Thunderstorms                                        19.4         67   0
 Thunderstorms,Heavy Rain Showers                      9.0         88   9
 Thunderstorms,Moderate Rain Showers,Fog              18.5         93  15
 Thunderstorms,Rain                                   18.2         83   4
 Thunderstorms,Rain Showers                            7.0         68   7
 Thunderstorms,Rain Showers,Fog                       16.1         80   7
 Thunderstorms,Rain,Fog                               18.6         88  19

                                          Visibility_km  Press_kPa
 WC
 Clear                                             11.3      99.52
 Cloudy                                            11.3      98.39
 Drizzle                                            6.4      97.84
 Drizzle,Fog                                        1.0      98.65
 Drizzle,Ice Pellets,Fog                            4.0     100.79
 Drizzle,Snow                                       9.7     100.63
 Drizzle,Snow,Fog                                   2.4      97.79
 Fog                                                0.2      98.31
 Freezing Drizzle                                   4.8      98.44
 Freezing Drizzle,Fog                               3.6      98.74
 Freezing Drizzle,Haze                              2.0     100.28
 Freezing Drizzle,Snow                              2.4      99.19
 Freezing Fog                                       0.2     101.97
 Freezing Rain                                      2.8      98.22
 Freezing Rain,Fog                                  2.8      98.32
 Freezing Rain,Haze                                 2.0     100.34
 Freezing Rain,Ice Pellets,Fog                      8.0     100.95
 Freezing Rain,Snow Grains                          4.8      98.56
 Haze                                               4.8     100.35
 Mainly Clear                                      12.9      98.67
 Moderate Rain,Fog                                  6.4      99.98
 Moderate Snow                                      0.6      99.88
 Moderate Snow,Blowing Snow                         0.6     100.50
 Mostly Cloudy                                     11.3      98.36
 Rain                                               4.0      97.52
 Rain Showers                                       6.4      98.51
 Rain Showers,Fog                                   6.4      99.83
 Rain Showers,Snow Showers                         19.3     101.09
 Rain,Fog                                           2.0      98.61
 Rain,Haze                                          4.0     100.50
 Rain,Ice Pellets                                   9.7     100.12

**Q) Show all the records where weather condition is fog.**

In [121]:
data[data['WC'] == 'Fog'].head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,WS,Visibility_km,Press_kPa,WC
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog

**Q) Find all instances when 'Weather is Clear' or 'Visibility is above 40'?**

In [129]:
x = data[data['WC'] == 'Clear'] 
y = data[data['Visibility_km'] > 40]
res = pd.merge(x,y,on='Date/Time')
res.head()

,Date/Time,Temp_C_x,Dew Point Temp_C_x,Rel Hum_%_x,WS_x,Visibility_km_x,Press_kPa_x,WC_x,Temp_C_y,Dew Point Temp_C_y,Rel Hum_%_y,WS_y,Visibility_km_y,Press_kPa_y,WC_y
0,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear,-15.4,-22.8,53,24,48.3,102.71,Clear
1,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear,-15.1,-22.8,52,24,48.3,102.79,Clear
2,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear,-11.3,-18.8,54,26,48.3,101.54,Clear
3,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear,-13.7,-18.4,68,19,48.3,101.84,Clear
4,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear,-12.7,-17.2,69,17,48.3,101.73,Clear

**Q) Find all instances when 'weather is clear' and 'relative humidity is greater than 50' or 'visibility is above 40'?**

In [131]:
x = data[(data['WC'] == 'Clear') & (data['Rel Hum_%'] > 50)]
y = data[data['Visibility_km'] > 40]
res = pd.merge(x,y,on='Date/Time')
res.head()

,Date/Time,Temp_C_x,Dew Point Temp_C_x,Rel Hum_%_x,WS_x,Visibility_km_x,Press_kPa_x,WC_x,Temp_C_y,Dew Point Temp_C_y,Rel Hum_%_y,WS_y,Visibility_km_y,Press_kPa_y,WC_y
0,1/15/2012 15:00,-15.4,-22.8,53,24,48.3,102.71,Clear,-15.4,-22.8,53,24,48.3,102.71,Clear
1,1/15/2012 16:00,-15.1,-22.8,52,24,48.3,102.79,Clear,-15.1,-22.8,52,24,48.3,102.79,Clear
2,1/18/2012 17:00,-11.3,-18.8,54,26,48.3,101.54,Clear,-11.3,-18.8,54,26,48.3,101.54,Clear
3,1/19/2012 8:00,-13.7,-18.4,68,19,48.3,101.84,Clear,-13.7,-18.4,68,19,48.3,101.84,Clear
4,1/19/2012 9:00,-12.7,-17.2,69,17,48.3,101.73,Clear,-12.7,-17.2,69,17,48.3,101.73,Clear